baseurl = "https://omaraparicio07.github.io/blog/"
languageCode = "en-us"
title = "Omar Aparicio"
theme = "m10c"
publishDir = "docs"
[params]
author = "Omar Aparicio"
description = "Estudiante de ingeniería en sistemas compitacionales en el IPN "
